### ISSUE TITLE
Vehicle Data: Location, Battery Level, Time Until Charged, and Outside Temp

### ISSUE THREAD

**Issue by MrTemple** [dburkland/tesla_cmds_aws_lambda_functions#3]
Love the shortcuts, even more so now that found your backend api and can pass in custom functions that aren't in the default shortcuts. I was using the RemoteApp, but the dang siri timeout was killing me.

Couple things that were available in the Tesla Remote App that I would love:

- current lat/lon (I've got a great "where are you" shortcut that takes the lat/lon and opens a walking route to it!)
- current battery level
- time until charged
- outside temperature

According to https://tesla-api.timdorr.com/vehicle/state/data, you can find them in the response under:

- vehicle_data>latitude/longitude (you're already getting this)
- charge_state>battery_level
- charge_state>minutes_until_full_charge (in minutes)
- charge_state>time_until_full_charge (in hours)
- climate_state>outside_temp

I was going to take a stab at a PR myself, but I see that you're not actually calling the vehicle_data api in GetVehicleData, and the format of the object you're accessing from just the vehicleid endpoint looks a bit different (has a "state" object, but not a "vehicle_state").

Really appreciate the work you've put in. Thanks!

**Comment by dburkland** [comment]
These shortcuts are now deprecated thanks to Tesla releasing native iOS shortcut support.
